
# Base Stage
FROM node:24-slim AS base-stage

WORKDIR /app

# Copy package.json and package-lock.json FIRST
COPY package.json package-lock.json ./

# Install dependencies with better network handling
RUN npm ci --verbose

# Copy the rest of the source code AFTER installing dependencies
COPY . .

# Development Stage
FROM base-stage AS dev-stage


ARG VITE_BACKEND_URL
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL

EXPOSE 5173

# Start the React app in development mode
CMD ["npm", "run", "dev"]



