# Docker Compose file for Starter template development
# Container names "st" for starter + "-" + service name e.g "st-backend"

services:
  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      # network: host
    container_name: st-backend
    restart: unless-stopped
    ports:
      - "8000:8000"

    volumes:
      - ./backend:/code
      - backend_cache:/code/.cache
      - /code/.venv
    networks:
      - st-network
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    container_name: st-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      network: host
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
      - "5173:5173" # Vite dev server
    # depends_on:
    #   - backend
    volumes:
      - ./frontend:/code
      - frontend_node_modules:/code/node_modules
      - frontend_cache:/code/.cache
    networks:
      - st-network
    command: npm run dev -- --host 0.0.0.0

  # Redis (Optional - for caching and sessions)
  redis:
    container_name: st-redis
    image: redis/redis-stack-server:latest
    ports:
      - "6378:6378"
    command: # list form is the safest
      - redis-server
      - --port
      - "6378"
      - --requirepass
      - "supersecret"
      - --loadmodule
      - /opt/redis-stack/lib/redisearch.so
      - --loadmodule
      - /opt/redis-stack/lib/rejson.so
    networks:
      - st-network

  postgres:
    image: postgres:17-alpine
    container_name: st-postgres
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - st-network
    env_file:
      - ./backend/.env

volumes:
  backend_cache:
    driver: local
  frontend_node_modules:
    driver: local
  frontend_cache:
    driver: local
  redis_data:
    driver: local

networks:
  st-network:
    driver: bridge
    name: st-network
