# Docker Compose file for Starter template prodelopment
# Container names "st" for starter + "-" + service name e.g "st-backend"

services:
  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      # network: host
    container_name: st-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - st-network
    depends_on:
      - redis
      - postgres
      - minio

  # React Frontend
  frontend:
    container_name: st-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_ENV=${VITE_ENV}
    restart: unless-stopped
    env_file: .env
    ports:
      - "81:81"
    depends_on:
      - backend
    networks:
      - st-network

  redis:
    container_name: st-redis
    image: redis/redis-stack-server:latest
    env_file:
      - ./backend/.env
    command:
      - redis-server
      - --port
      - "6378"
      - --requirepass
      - "${REDIS_PASSWORD}"
      - --loadmodule
      - /opt/redis-stack/lib/redisearch.so
      - --loadmodule
      - /opt/redis-stack/lib/rejson.so
    networks:
      - st-network

  postgres:
    image: postgres:17-alpine
    container_name: st-postgres
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    # ports:
    #   - "5432:5432"
    networks:
      - st-network
    env_file:
      - ./backend/.env

  minio:
    container_name: st-minio
    image: minio/minio:latest
    command: server /data --console-address ":9003"
    # ports:
    #   - "9002:9002" # MinIO API Port
    #   - "9003:9003" # MinIO Console Port
    volumes:
      # - /mnt/volume-nbg1-1/minio_data:/data
      - minio_data:/data
    env_file:
      - ./backend/.env
    networks:
      - st-network

volumes:
  backend_cache:
    driver: local
  frontend_node_modules:
    driver: local
  frontend_cache:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  st-network:
    driver: bridge
    name: st-network
