FROM python:3.12-slim-bookworm


RUN apt-get update && apt-get install -y build-essential

COPY --from=ghcr.io/astral-sh/uv:0.8.10 /uv /uvx /bin/

ADD . /app

WORKDIR /app


RUN uv sync

ENV PATH="/app/.venv/bin:$PATH"


CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "main:main", "--bind", "0.0.0.0:8000"]
