[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.16.4",
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.116.1",
    "posthog>=6.1.1",
    "psycopg2-binary>=2.9.10",
    "pydantic-settings>=2.10.1",
    "pyjwt>=2.10.1",
    "python-json-logger>=3.3.0",
    "pyyaml>=6.0.2",
    "ruff>=0.12.3",
    "sqlalchemy>=2.0.41",
]


[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[project.scripts]
hello = "scripts.hello:main"

[tool.setuptools]
packages = ["scripts"]

[tool.poe]
executor.type = "uv"

[tool.poe.tasks]
dev = "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
lint = "ruff check ."
## uv run poe migrate "add user table"
migrate = { cmd = "alembic --config pyproject.toml revision --autogenerate -m $msg", help = "Generate a new Alembic migration with a message", env = { msg = "" } }


[tool.alembic]
# path to migration scripts
script_location = "%(here)s/alembic"

file_template = "%%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
