events {
    worker_connections 1024;
}


http {

    server {
        listen 80;
        server_name cognaite.com www.cognaite.com
        return 301 https://$host$request_uri;
    }
    ## only needed for load balancing
    # upstream frontend {
    #     server ceph-frontend:5173;
    # }

    # upstream backend {
    #     server ceph-backend:8000;
    # }
    # upstream frontend {
    #     server ceph-frontend:80;
    # }
    # add_header Content-Security-Policy "
    #   default-src 'self' https: data: blob:;
    #   script-src  'self' https: 'unsafe-inline' 'unsafe-eval';
    #   style-src   'self' https: 'unsafe-inline';
    #   img-src     'self' https: data: blob:;
    #   connect-src 'self' https: wss:;
    #   font-src    'self' https: data:;
    #   frame-src   'self' https:;
    # " always;

# add_header Content-Security-Policy "
#   default-src 'self';
#   script-src 'self' https://js.stripe.com https://eu-assets.i.posthog.com https://accounts.google.com 'unsafe-inline';
#   style-src 'self' https://fonts.googleapis.com 'unsafe-inline';
#   font-src 'self' https://fonts.gstatic.com;
#   img-src 'self' data:;
#   frame-src https://js.stripe.com https://accounts.google.com;
#   connect-src 'self';
# " always;


    # Security headers (optional but recommended)
    # add_header X-Frame-Options "SAMEORIGIN" always;
    # add_header X-Content-Type-Options "nosniff" always;
    # add_header Referrer-Policy "no-referrer-when-downgrade" always;
    # add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;" always;


    server {
        listen 443 ssl;
        server_name cognaite.com www.cognaite.com;

        ssl_certificate      /etc/ssl/cloudflare/origin.crt;
        ssl_certificate_key  /etc/ssl/cloudflare/origin.key;

        location / {
            proxy_pass http://localhost:80;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Optional: WebSocket Timeout Adjustments
            proxy_read_timeout 86400;
            proxy_send_timeout 86400;
        }

        location /api/ {
            proxy_pass http://localhost:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


        location /api/user/auth/callback/ {
            proxy_pass http://localhost:8000/user/auth/callback;


        location /minio/ {
            rewrite ^/minio(/.*)$ $1 break;
            proxy_pass http://localhost:9002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /minio-console/ {
            rewrite ^/minio-console(/.*)$ $1 break;
            proxy_pass http://localhost:9003;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Additional headers required by MinIO Console
            proxy_http_version 1.1;
            proxy_set_header Connection '';
            chunked_transfer_encoding off;
            proxy_buffering off;
            proxy_cache off;
        }

    }
}
}
