/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as RegisterIndexRouteImport } from './routes/Register/index'
import { Route as ReadmeIndexRouteImport } from './routes/Readme/index'
import { Route as LoginIndexRouteImport } from './routes/Login/index'
import { Route as LicenseIndexRouteImport } from './routes/License/index'
import { Route as AccountIndexRouteImport } from './routes/Account/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/Register/',
  path: '/Register/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadmeIndexRoute = ReadmeIndexRouteImport.update({
  id: '/Readme/',
  path: '/Readme/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/Login/',
  path: '/Login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseIndexRoute = LicenseIndexRouteImport.update({
  id: '/License/',
  path: '/License/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/Account/',
  path: '/Account/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Account': typeof AccountIndexRoute
  '/License': typeof LicenseIndexRoute
  '/Login': typeof LoginIndexRoute
  '/Readme': typeof ReadmeIndexRoute
  '/Register': typeof RegisterIndexRoute
  '/about': typeof AboutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Account': typeof AccountIndexRoute
  '/License': typeof LicenseIndexRoute
  '/Login': typeof LoginIndexRoute
  '/Readme': typeof ReadmeIndexRoute
  '/Register': typeof RegisterIndexRoute
  '/about': typeof AboutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Account/': typeof AccountIndexRoute
  '/License/': typeof LicenseIndexRoute
  '/Login/': typeof LoginIndexRoute
  '/Readme/': typeof ReadmeIndexRoute
  '/Register/': typeof RegisterIndexRoute
  '/about/': typeof AboutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Account'
    | '/License'
    | '/Login'
    | '/Readme'
    | '/Register'
    | '/about'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Account'
    | '/License'
    | '/Login'
    | '/Readme'
    | '/Register'
    | '/about'
  id:
    | '__root__'
    | '/'
    | '/Account/'
    | '/License/'
    | '/Login/'
    | '/Readme/'
    | '/Register/'
    | '/about/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountIndexRoute: typeof AccountIndexRoute
  LicenseIndexRoute: typeof LicenseIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ReadmeIndexRoute: typeof ReadmeIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Register/': {
      id: '/Register/'
      path: '/Register'
      fullPath: '/Register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Readme/': {
      id: '/Readme/'
      path: '/Readme'
      fullPath: '/Readme'
      preLoaderRoute: typeof ReadmeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Login/': {
      id: '/Login/'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/License/': {
      id: '/License/'
      path: '/License'
      fullPath: '/License'
      preLoaderRoute: typeof LicenseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Account/': {
      id: '/Account/'
      path: '/Account'
      fullPath: '/Account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountIndexRoute: AccountIndexRoute,
  LicenseIndexRoute: LicenseIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ReadmeIndexRoute: ReadmeIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  AboutIndexRoute: AboutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
